[workspace]
members = ["cli", "gfw"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.82"
clap = { features = ["derive"], version = "4.5.4" }
reqwest = { features = ["json"], version = "0.12.3" }
serde = { features = ["derive"], version = "1.0.197" }
serde_json = "1.0.115"
tokio = { features = ["full"], version = "1.37.0" }
tracing = "0.1.40"

[workspace.package]
edition = "2021"
version = "0.0.0"
