[dependencies]
cli = { path = "../cli" }
colored = "2.1.0"
console = "0.15.8"
serde_json = "1.0.115"
tabled = { features = ["ansi"], version = "0.15.0" }
anyhow.workspace = true
clap.workspace = true
reqwest.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true

[package]
name = "gfw"
edition.workspace = true
version.workspace = true
