[dependencies]
clap-verbosity-flag.workspace = true
colored.workspace = true
concolor-clap.workspace = true
console.workspace = true
shadow-rs.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[package]
name = "cli"
edition.workspace = true
version.workspace = true
