[dependencies]
api = { path = "../../lib/api" }
cli = { path = "../../lib/cli" }
anyhow.workspace = true
clap.workspace = true
clap-verbosity-flag.workspace = true
colored.workspace = true
concolor-clap.workspace = true
confy.workspace = true
directories.workspace = true
ipnet.workspace = true
local-ip-address.workspace = true
once_cell.workspace = true
serde.workspace = true
tabled.workspace = true
tokio.workspace = true
tracing.workspace = true
whoami.workspace = true

[package]
name = "cf"
edition.workspace = true
version.workspace = true
