[dependencies]
api = { path = "../../lib/api" }
cli = { path = "../../lib/cli" }
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
clap-verbosity-flag.workspace = true
colored.workspace = true
concolor-clap.workspace = true
confy.workspace = true
console.workspace = true
indicatif.workspace = true
once_cell.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tabled.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

[package]
name = "gfw"
edition.workspace = true
version.workspace = true
