name: CI

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Toolchain
        run: rustup default stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install Tools
        uses: liblaf/repo/.github/actions/install@main
        with:
          brew: coreutils make
          choco: gnuwin32-coreutils.install gnu-make
      - name: Build
        run: make dist
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.arch }}-${{ runner.os }}
          path: dist/
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Create GitHub Release
        uses: liblaf/template/.github/actions/release@main
        with:
          tag: dev
          files: "*"
          prerelease: true
