name: CI

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Toolchain
        run: rustup default stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install Tools
        uses: liblaf/repo/.github/actions/install@main
        with:
          brew: coreutils gnu-sed make
          choco: gnuwin32-coreutils.install make sed
      - name: Build
        run: make dist
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.arch }}-${{ runner.os }}
          path: dist/
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - build
    if: always() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist
          merge-multiple: true
      - name: Create GitHub Release
        uses: liblaf/repo/.github/actions/release@main
        with:
          tag: dev
          files: dist/*
          pre-release: true
          recreate: true
